USE [QLKhachSan]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[MAHD] [int] IDENTITY(1,1) NOT NULL,
	[SONGAYO] [int] NOT NULL,
	[MANV] [int] NOT NULL,
	[TONGTIEN] [int] NOT NULL,
	[TENKH] [nvarchar](50) NOT NULL,
	[TENPHONG] [nvarchar](50) NOT NULL,
	[NGAYLAPHD] [datetime] NOT NULL,
	[NGAYDAT] [datetime] NOT NULL,
	[TYLEPHUTHU] [float] NOT NULL,
	[CCCD] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED 
(
	[MAHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [int] IDENTITY(1,1) NOT NULL,
	[TENKH] [nvarchar](30) NOT NULL,
	[TUOI] [int] NOT NULL,
	[TEL] [nvarchar](12) NOT NULL,
	[DIACHIKH] [nvarchar](100) NULL,
	[CMNDKH] [nvarchar](50) NOT NULL,
	[MALOAIKHACH] [int] NOT NULL,
	[MAP] [int] NOT NULL,
 CONSTRAINT [PK_KHACH] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIKHACH]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIKHACH](
	[MALOAIKHACH] [int] IDENTITY(1,1) NOT NULL,
	[TENLOAIKHACH] [nchar](20) NULL,
 CONSTRAINT [PK_LOAIKHACH] PRIMARY KEY CLUSTERED 
(
	[MALOAIKHACH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIPHONG]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIPHONG](
	[MALOAIPHONG] [int] IDENTITY(1,1) NOT NULL,
	[TENLOAI] [nvarchar](30) NOT NULL,
	[DONGIA] [int] NOT NULL,
 CONSTRAINT [PK_LOAIPHONG] PRIMARY KEY CLUSTERED 
(
	[MALOAIPHONG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [int] IDENTITY(1,1) NOT NULL,
	[HOTEN] [nvarchar](30) NOT NULL,
	[PHAI] [nchar](3) NOT NULL,
	[NGAYSINH] [date] NOT NULL,
	[SDT] [nvarchar](12) NOT NULL,
	[EMAIL] [nvarchar](100) NOT NULL,
	[DIACHI] [nvarchar](100) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUTHUE]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUTHUE](
	[MAPT] [int] IDENTITY(1,1) NOT NULL,
	[NGAYLAPPT] [datetime] NOT NULL,
	[MAKH] [int] NOT NULL,
	[MAP] [int] NOT NULL,
	[CCCD] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[MAPT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHONG]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHONG](
	[MAP] [int] IDENTITY(1,1) NOT NULL,
	[TENPHONG] [nvarchar](30) NOT NULL,
	[TINHTRANG] [int] NOT NULL,
	[SOLUONGKHACHTOIDA] [int] NOT NULL,
	[GHICHU] [text] NULL,
	[MALOAIPHONG] [int] NOT NULL,
	[SONGAYO] [int] NOT NULL,
 CONSTRAINT [PK_PHONG] PRIMARY KEY CLUSTERED 
(
	[MAP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHUTHU]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHUTHU](
	[IDPhuthu] [int] IDENTITY(1,1) NOT NULL,
	[Giatriphuthu] [float] NOT NULL,
 CONSTRAINT [PK_PHUTHU] PRIMARY KEY CLUSTERED 
(
	[IDPhuthu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAIKHOAN]    Script Date: 11/3/2024 5:08:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
	[MATKNV] [int] IDENTITY(1,1) NOT NULL,
	[TENTKNV] [nchar](40) NOT NULL,
	[MKTK] [nchar](30) NOT NULL,
	[MANV] [int] NOT NULL,
 CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY CLUSTERED 
(
	[MATKNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[LOAIKHACH] ON 
GO
INSERT [dbo].[LOAIKHACH] ([MALOAIKHACH], [TENLOAIKHACH]) VALUES (1, N'Khách mới           ')
GO
INSERT [dbo].[LOAIKHACH] ([MALOAIKHACH], [TENLOAIKHACH]) VALUES (2, N'Khách cũ            ')
GO
SET IDENTITY_INSERT [dbo].[LOAIKHACH] OFF
GO
SET IDENTITY_INSERT [dbo].[LOAIPHONG] ON 
GO
INSERT [dbo].[LOAIPHONG] ([MALOAIPHONG], [TENLOAI], [DONGIA]) VALUES (1, N'VIP-1', 1000000)
GO
INSERT [dbo].[LOAIPHONG] ([MALOAIPHONG], [TENLOAI], [DONGIA]) VALUES (2, N'VIP-2', 2500000)
GO
INSERT [dbo].[LOAIPHONG] ([MALOAIPHONG], [TENLOAI], [DONGIA]) VALUES (3, N'Thường', 700000)
GO
SET IDENTITY_INSERT [dbo].[LOAIPHONG] OFF
GO
SET IDENTITY_INSERT [dbo].[NHANVIEN] ON 
GO
INSERT [dbo].[NHANVIEN] ([MANV], [HOTEN], [PHAI], [NGAYSINH], [SDT], [EMAIL], [DIACHI]) VALUES (1, N'Nguyễn Thanh Tùng', N'Nam', CAST(N'2004-08-08' AS Date), N'0918345885', N'trunbnguyen@gmail.com', N'số 3 Nguyễn Khánh Toàn')
GO
SET IDENTITY_INSERT [dbo].[NHANVIEN] OFF
GO
SET IDENTITY_INSERT [dbo].[PHONG] ON 
GO
INSERT [dbo].[PHONG] ([MAP], [TENPHONG], [TINHTRANG], [SOLUONGKHACHTOIDA], [GHICHU], [MALOAIPHONG], [SONGAYO]) VALUES (1, N'Phòng101', 1, 5, NULL, 1, 0)
GO
INSERT [dbo].[PHONG] ([MAP], [TENPHONG], [TINHTRANG], [SOLUONGKHACHTOIDA], [GHICHU], [MALOAIPHONG], [SONGAYO]) VALUES (2, N'Phòng102', 1, 5, NULL, 2, 0)
GO
INSERT [dbo].[PHONG] ([MAP], [TENPHONG], [TINHTRANG], [SOLUONGKHACHTOIDA], [GHICHU], [MALOAIPHONG], [SONGAYO]) VALUES (3, N'Phòng103', 1, 3, NULL, 3, 0)
GO
INSERT [dbo].[PHONG] ([MAP], [TENPHONG], [TINHTRANG], [SOLUONGKHACHTOIDA], [GHICHU], [MALOAIPHONG], [SONGAYO]) VALUES (4, N'Phòng104', 1, 3, NULL, 1, 0)
GO
INSERT [dbo].[PHONG] ([MAP], [TENPHONG], [TINHTRANG], [SOLUONGKHACHTOIDA], [GHICHU], [MALOAIPHONG], [SONGAYO]) VALUES (5, N'Phòng105', 1, 4, NULL, 1, 0)
GO
SET IDENTITY_INSERT [dbo].[PHONG] OFF
GO
SET IDENTITY_INSERT [dbo].[PHUTHU] ON 
GO
INSERT [dbo].[PHUTHU] ([IDPhuthu], [Giatriphuthu]) VALUES (1, 30)
GO
SET IDENTITY_INSERT [dbo].[PHUTHU] OFF
GO
SET IDENTITY_INSERT [dbo].[TAIKHOAN] ON 
GO
INSERT [dbo].[TAIKHOAN] ([MATKNV], [TENTKNV], [MKTK], [MANV]) VALUES (6, N'trunbnguyen@gmail.com                   ', N'123456789                     ', 1)
GO
SET IDENTITY_INSERT [dbo].[TAIKHOAN] OFF
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD  CONSTRAINT [FK_HOADON_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[HOADON] CHECK CONSTRAINT [FK_HOADON_NHANVIEN]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_KHACHHANG_LOAIKHACH] FOREIGN KEY([MALOAIKHACH])
REFERENCES [dbo].[LOAIKHACH] ([MALOAIKHACH])
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_KHACHHANG_LOAIKHACH]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [FK_KHACHHANG_PHONG1] FOREIGN KEY([MAP])
REFERENCES [dbo].[PHONG] ([MAP])
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [FK_KHACHHANG_PHONG1]
GO
ALTER TABLE [dbo].[PHIEUTHUE]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTHUE_KHACHHANG1] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[PHIEUTHUE] CHECK CONSTRAINT [FK_PHIEUTHUE_KHACHHANG1]
GO
ALTER TABLE [dbo].[PHIEUTHUE]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUTHUE_PHONG] FOREIGN KEY([MAP])
REFERENCES [dbo].[PHONG] ([MAP])
GO
ALTER TABLE [dbo].[PHIEUTHUE] CHECK CONSTRAINT [FK_PHIEUTHUE_PHONG]
GO
ALTER TABLE [dbo].[PHONG]  WITH CHECK ADD  CONSTRAINT [FK_PHONG_LOAIPHONG] FOREIGN KEY([MALOAIPHONG])
REFERENCES [dbo].[LOAIPHONG] ([MALOAIPHONG])
GO
ALTER TABLE [dbo].[PHONG] CHECK CONSTRAINT [FK_PHONG_LOAIPHONG]
GO
ALTER TABLE [dbo].[TAIKHOAN]  WITH CHECK ADD  CONSTRAINT [FK_TAIKHOAN_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[TAIKHOAN] CHECK CONSTRAINT [FK_TAIKHOAN_NHANVIEN]
GO
